// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://leghrjgcasbtrbnhhuuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlZ2hyamdjYXNidHJibmhodXV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyODQ0MDcsImV4cCI6MjA2ODg2MDQwN30.7d6yvmFaTAsVB9UiwgI8e8YustoU1y_a7TitsuD9Nhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});